export const Colors = {
  buttonBackgroundColor: '#ff4d6d',
  buttonTextColor: '#fff0f3',
  modalBackgroundColor: '#bbd0ff',
  modalShaddowcolor: '#000',
  editIconColor: 'red',
  deleteIconColor: 'red',
  goalListBackgroundColor: '#ff4d6d',
  listTitleTextColor: 'white',
  listTextColor: 'white',
  completeTaskContainerBorderTopColor: '#5a189a',
  completeTaskContainerBorderBottomColor: '#5a189a',
  completeTaskContainerBorderLeftColor: '#5a189a',
  completeTaskContainerBorderRightColor: '#5a189a',
  flatListMainViewBackgroundColor: '#5a189a',
  countTextColor: 'green',
  countBorderColor: 'green',
  goalInputColor: 'green',
  errorGoalInputColor: 'red',
};
